### ISSUE TITLE
Scan an assembly in order to create a XmlContentSerializer

### ISSUE THREAD

**Issue by ploeh** [GreanTech/AtomEventStore#101]
Now that `XmlContentSerializer` has a `CreateTypeResolver` method, it's possible to create an instance like this:

``` C#
var serializer = new XmlContentSerializer(
    XmlContentSerializer.CreateTypeResolver(
        typeof(UserCreated).Assembly));
```

This is better than having to manually create an instance of `TypeResolutionTable`, but now that the building blocks are in place, it'd be nice with an even easier short-cut:

``` C#
XmlContentSerializer serializer =
    XmlContentSerializer.Scan(typeof(UserCreated).Assembly);
```

In the above example, this method is called `Scan`, but other alternatives are possible:
- Scan
- Create
- CreateSerializer
- CreateContentSerializer

**Comment by moodmosaic** [comment]
Hm... _Scan_ is easy to understand, _if_ you already know about this:

``` c#
var serializer = new XmlContentSerializer(
    XmlContentSerializer.CreateTypeResolver(
        typeof(UserCreated).Assembly));
```

_Create_ makes it easier to understand what the return type is.

**Comment by ploeh** [comment]
Yes, but _Scan_ provides a hint about what's actually going on.

My concern about _Create_ is that, based on an `Assembly` as input, it sounds a bit magical.

**Comment by moodmosaic** [comment]
Agreed. And it's probably more important to know what's actually going on (_vs_ what's returned).
