### ISSUE TITLE
Single Writer Pattern

### ISSUE THREAD

**Issue by tmasternak-infusion** [GreanTech/AtomEventStore#108]
Reading the documentation I found information that writes should be performed using Single Writer pattern. My understanding is that one of possible usages of AtomEventStore is persistence for Event Sourcing scenarios. 
Assuming my understanding is correct it is not clear to me how to achieve that with: 
 a. single process/role writing to a store
 b. multiple processes/roles writing to a store

Finally is it possible to achieve optimistic concurrency on aggregate version with AtomEventStore?

**Comment by ploeh** [comment]
Thank you for writing. In an effort to answer your questions, I've added [a document about the Single Writer pattern](https://github.com/GreanTech/AtomEventStore/wiki/Single-Writer) to the wiki.

Your question about optimistic concurrency should be [answered already](https://github.com/GreanTech/AtomEventStore/wiki/Lock-free):

> Since _Optimistic Concurrency can't be guaranteed_ by all storage implementations, the clients have the responsibility to prevent concurrency conflicts.

(my emphasis)

**Comment by tmasternak-infusion** [comment]
Thank you very much for in depth explanation! It clarified a lot my understanding of AtomEventStore.
