### ISSUE TITLE
Storage as a doubly linked list

### ISSUE THREAD

**Issue by ploeh** [GreanTech/AtomEventStore#48]
As we've discussed off-line, it would be beneficial if we could treat the Atom storage model as a [doubly linked list](http://en.wikipedia.org/wiki/Doubly_linked_list).
# Current implementation

Right now, it's only a unidirectional linked list, starting at the most recent entry.
## Advantages

This implementation has the advantages that it's optimised for writing, and for reading only the latest entries:
- It's optimised for writing because the identity of an event sequence is defined by the 'index', which is the ID of the page containing the most recent entries. Thus, when a writer appends a new entry, it can append the new entry directly to the index. This is an O(1) operation.
- It's optimized for reading latest entries because a reader can start with the most recent entry, and then move back in time until it encounters an entry it's already seen. If done frequently, this will often be a fast operation too, because a reader doesn't have to move particularly far back.
## Disadvantages

The current implementation has the disadvantage that it's expensive to read the entire event sequence. The current iterator starts with the most recent entry and moves back in time. Unless the client breaks out of the loop prematurely, iteration continues until the first/oldest entry is reached.

However, when entries are events, events must be played back in the correct order when interpreted. This means that a client must keep _all_ events in memory, and only when iteration stops can it reverse the sequence and play back the events. This doesn't scale, because for long sequences, the client will run out of memory before it reaches the oldest entry.

If we can move in both directions, it would be more flexible, and enable more scenarios.
# A bit of Atom nomenclature

Before we discuss alternatives, let's review the Atom nomenclature, in order to be sure that we're on the same page.

An Atom **Feed** logically consists of an arbitrary number of Atom Entries.

An Atom **Entry** contains the data we store; in our case events (or, normally, changesets of events).

Most recent entries appear first in the Feed.

While a Feed is logically only a single, unbroken (ordered) collection of Entries, in practice, a Feed is made up of a number of XML _documents_ (or pages). The documents can link to each other using Atom Links.

An Atom **Link** is an XML element with some important attributes:
- _href_ is the address (URI) of the link
- _rel_ is the relationship type of the link. It indicates what a client can expect to find at that address; e.g. the previous page in a collection of documents.

Atom defines some common _rel_ values:
- _self_ indicates the resource itself
- _previous_ indicates the immediately previous page. Depending on your perspective, you can think of 'previous' as indicating something that was created previously in time, or as the page you previously looked at. The last of these two definitions is ambiguous, as it depends on your order of traversal, so in AtomEventStore, we use the definition that _previous_ indicates pages (and entries) that were previously created, and thus, represents older data.
- _next_ is the opposite of _previous_. In AtomEventStore, we use the definition that _next_ indicates pages (and entries) that are newer than the current page.
- _first_, by the same token, indicates the first (and thereby oldest) page ever written as part of the event sequence.
- _last_ is the opposite of _first_. In AtomEventStore, it indicates the newest page in the event sequence.
# Alternative 1

As we've also discussed off-line, if we let the ID of the sequence be the oldest (_first_) page, it would be possible to append new pages as entries are added.

Assuming a page size of _n_, as long as there are less than _n_ entries, we can simply update the Feed document. As this is an update operation on a single document, we can protect this operation against concurrency issues by using optimistic concurrency (e.g. ETags in HTTP APIs).

When we're about to add element number _n + 1_, we create a new Feed document and write the new Entry in the new new document. We also add _previous_ and _first_ links, pointing to the first page. When that write operation completes, we update the _first_ page by adding a _next_ link, pointing to the new document. This update operation is also protected with optimistic concurrency, so if the update fails, we consider the entire operation failed, and the client would have to retry. This would leave the newly created page orphaned, but a background job could clean it up later.

When we're about to add element number _n \* 2 + 1_, almost the same set of operations happen again:
1. Create a new Feed document and write the new Entry in the new document. Also add a _previous_ link, pointing to the previous page, and a _first_ link, pointing to the first page.
2. Update the previous page by adding a _next_ link that points to the new document. This update is again protected by optimistic concurrency.

This process can be repeated for every entry number _n \* m + 1_, where _m_ is the number of pages.

Notice that while all pages have a _first_ link, no pages have a _last_ link.
## Advantages

The advantages of this alternative is that a client can replay events in the order they originally happened, because iteration will start at _first_ and follow _next_ links until there are no more entries.

It's also possible for a client to bookmark the latest entry it's seen, and then iterate only through those entries that are newer than the last entry it knew about.
## Disadvantages

However, as AtomEventStore doesn't surface the addresses of each Feed document, a bookmarking feature would have to be implemented as a stateful Iterator that remembers the most recent Entry it served last.

In off-line discussions, we've called such a class a `ForwardReadOnlyCursor<T>`. The first time a client enumerates all items, it starts at _first_ and follows _next_ links until it has enumerated all entries. It then stores the Entry's ID, as well as the containing Feed ID in an internal variable.

The next time a client enumerates the `ForwardReadOnlyCursor<T>`, it starts where it left off before, and again keeps moving until it's reached the most recent Entry. Again, it stores the most recent Entry's ID, as well as the container Feed ID.

In order to be thread-safe, it must ensure that concurrent clients don't enumerate the same items, so that adds extra complexity.

In addition to that, it's currently unclear to me what would happen if a client starts to enumerate, but breaks off before the most recent Entry is reached (e.g. by invoking the  `First()` LINQ method).

Basically, this design violates CQS, which indicates to me that something is wrong with the design.

Another disadvantage is that because _last_ is unknown, write operations become inefficient. In order to write to the _last_ page, a client would have to start at _first_ and then follow all _next_ links until it reaches the most recent page.

Again, a writer could be stateful and remember where it last wrote, so that it only has to follow _next_ links until it reaches the most recent page, but that still adds complexity.
# Alternative 2

This suggestion builds on Alternative 1, but attempts to also maintain a _last_ link on _first_.

It could work like this:

Assume, again, that _n_ indicates the page size. For the first _n_ Entries, a writer simply updates the first page, using optimistic concurrency. The first page contains a _last_ link, pointing to itself.

When a writer has to add Entry number _n + 1_, it creates a new document like in alternative 1. When it updates the first page, not only does it add a _next_ link, but it also updates the _last_ link to point to the new document. This is still a 'create' operation followed by a single 'update' operation, so it's still safe.

When a writer has to add Entry number _n \* 2 + 1_, it create a new document like in alternative 1. It both updates the previous document by adding a _next_ link, but then it also updates the first document by updating its _last_ link.

This is one 'create' operation followed by _two_ 'update' operations. While both updates are individually protected by optimistic concurrency, they are not enlisted in a distributed transaction. Thus, there's a risk that one of them might fail. What happens if this is the case?

The write operations happen in strict sequence: 'create', 'update', 'update'. The next operation will only be attempted if the previous operation succeeded.
- If the 'create' operation fails, no harm is done. The Entry is _not_ written to persistent storage, and the client would have to retry.
- If the first 'update' operation fails, the new Feed document is orphaned. While the Entry is written to persistent storage, no links point to it. The client must retry, and a background job can delete the orphaned file.
- If the second 'update' operation fails, the new Entry is written, and all _next_ and _previous_ links are consistent. However, the _last_ link in the first document may not be pointing to the most recent Feed page - or what? Assuming that the 'update' operation fails because of a concurrency conflict, what does a concurrency conflict indicate? If all clients follow this 'create', 'update', 'update' protocol, the _only reason to update the first page is to update the *last_ link_. We know that the first part of the protocol ('create', 'update') guarantees that if these two operations succeed, all *next_ and _previous_ links are consistent and valid, so the only problem is to ensure that the _last_ link points to the correct page.

Let's further examine how concurrency conflicts can occur for the second update. As the page size grows, this becomes more and more unlikely, so consider the degenerate case where the page size is _1_.

Imaging that we have already have 3 pages. Here are some scenarios:
## Scenario 1
1. Writer1 creates a new document, _page4_
2. Writer1 updates _page3_ with a link to _page4_
3. Writer2 creates a new document, _page5_
4. Writer2 updates _page4_ with a link to _page5_
5. Writer1 updates _page1_ with a link to _page4_. This is possible, because _page1_ hasn't changed yet.
6. Writer2 attempts to update _page1_ with a link to _page5_. However, this fails because _page1_ was already updated. This is not OK, because it leaves the _last_ link on _page1_ pointing to _page4_
## Scenario 2
1. Writer1 creates a new document, _page4_
2. Writer1 updates _page3_ with a link to _page4_
3. Writer2 creates a new document, _page5_
4. Writer2 updates _page4_ with a link to _page5_
5. Writer2 updates _page1_ with a link to _page5_. This is possible, because _page1_ hasn't changed yet.
6. Writer1 attempts to update _page1_ with a link to _page4_. However, this fails because _page1_ was already updated. However, this is OK, because the _last_ link in _page1_ already points to _page5_.
## Scenario 3
1. Writer1 creates a new document, _page4_
2. Writer1 updates _page3_ with a link to _page4_
3. The client crashes. This is not OK, because it leaves the _last_ link on _page1_ pointing to _page3_.

It seems to me that, while it's not possible to guarantee that the _last_ link on the first page always points to the true last page, it'll always point to a real, existing page. Thus, AtomEventStore could adopt the pragmatic approach that in order to reach the most recent page, it can follow the _last_ link, then attempt to follow _next_ links, if any are present.

That does slightly bend the semantics of a _last_ link, but would it work, or is there a flaw in my logic?
## Advantages

The advantages of having doubly-linked lists with _first_ and (best-effort) _last_ links is that it becomes possible to offer stateless traversal in both directions.

In order to replay _all_ events, a client starts at _first_ (which is also the known 'address' of the feed), and then follows _next_ links until all items have been enumerated.

In order to get only the events since a last known event, a client starts at _first_, follows the _last_ link, further follows _next_ links if any are present, then starts iterating from the most recent Entry backwards, following _previous_ links.

In order to write a new Entry, a client starts at _first_, follows the _last_ link, further follows _next_ links if any are present, then writes the new Entry to the most recent page.
## Disadvantages

This alternative slightly bends the semantics of what _last_ means. Also, I need a second opinion on this, because I wonder if the system could get into some sort of race where _last_ is never updated... I can't see how that would happen, but I don't feel certain that it can't.

My intuition is that as the page size grows, the probability of a concurrency conflict when updating the _last_ link decreases, but if there's one thing I've learned about concurrency design, it's that you can't rely on probabilities.

**Comment by sgryt** [comment]
Some initial questions about the disadvantages of Alternative 1

> In addition to that, it's currently unclear to me what would happen if a client starts to enumerate, but breaks off before the most recent Entry is reached (e.g. by invoking the First() LINQ method).

That would correspond to a client that has gotten out of sync due to other clients writing new data, AFAICT. Seems aligned with the general requirement of being able to have multiple writers for the event stream?

> Basically, this design violates CQS, which indicates to me that something is wrong with the design.

Why is that? It's a state machine, as are all iterator implementations AFAIA. Are there any persistent side effects of querying in this design? 

> Another disadvantage is that because last is unknown, write operations become inefficient. In order to write to the last page, a client would have to start at first and then follow all next links until it reaches the most recent page.

I have a hard time imagining the use case where it is safe to write new data without first reading the existing data? In that case, why choose an event stream at all? 

About Alternative 2 - if I understand you correctly, it builds on Alternative 1, so the same disadvantages apply, yes?

I'll start digging into the scenarios now. BRB.

**Comment by sgryt** [comment]
Observation: The 'last' link only makes sense for the first page. We will not be able to maintain it in the rest of the pages. Trivial, perhaps, but makes for an asymmetry in the model.

**Comment by sgryt** [comment]
First off, here's my own reasoning. I thought it would be useful with 2 independent views on the situation, before reviewing your scenarios. I will look into them next.

I think there are 5 scenarios to consider, for completeness. Two of them are 'solo accidents' while two involve 2 writers. A special case of creating the second page (which involves only 1 update, namely the 'next' and 'last' links on Page1) is also relevant.

As the CREATE stage will never give rise to conflicts (if it succeeds), we can leave it out of the consideration on whether or not we can end up in an inconsistent state. The client may choose to retry, but there is no debris left behind if creating the new page fails.
Also, the scenarios are symmetric wrt which writer is designated 'first' and 'second', respectively, so it is not necessary to consider writer-number-permutation cases.

Scenarios after creating page # N+1 (N >= 2):

Solo accidents 
1. Updating the 'next' link on Page N fails. This results in a stale page left behind from the CREATE step. As no UPDATE precedes this step, no inconsistency is possible.
2. Updating the 'next' link on Page N succeeds, but updating the 'last' link on Page 1 fails. This results in a stale 'last' link on Page 1, but the rest of the data is consistent (Page N 'next' link points to Page N+1).

Multiple (2) writer conflicts
3. Writer2 fails to update the 'next' link on Page N because Writer1 updated Page N first. This results in a stale page from Writer2's CREATE step, but is otherwise completely analogous to the first solo accident case. Again, as no UPDATE from Writer2 precedes this step, no inconsistency is possible.
4. Writer2 fails to update the 'next' link on Page N AND Writer1 fails to update the 'last' link on Page 1. This results in a stale page from Writer2, and a stale 'last' link on Page 1. But the 'next' link on Page N correctly points to Page N+1, so there are no inconsistencies.

Special case of creating Page 2
As mentioned above, this can (and should) be handled by a single update to Page 1, setting both the 'next' and 'last' links in one go. If so, only the stale page scenario is relevant here, and inconsistencies cannot arise from that.

**Comment by ploeh** [comment]
_Solo accidents_ - I like that :)

Thank you for writing out the failure scenarios once more. As far as I can tell, you reach the same conclusion that I have reached: that all _next_, _previous_, and _first_ links are going to be correct, but that the _last_ link may be stale.

> > In addition to that, it's currently unclear to me what would happen if a client starts to enumerate, but breaks off before the most recent Entry is reached (e.g. by invoking the First() LINQ method).
> 
> That would correspond to a client that has gotten out of sync due to other clients writing new data, AFAICT. Seems aligned with the general requirement of being able to have multiple writers for the event stream?

What I had in mind was that the implementation of a hypothetical `ForwardReadOnlyCursor<T>` would update its internal 'bookmark' state whenever it's done enumerating, but will it ever know that the client is done, if the client breaks off prematurely?

> > Basically, this design violates CQS, which indicates to me that something is wrong with the design.
> 
> Why is that? It's a state machine, as are all iterator implementations AFAIA. Are there any persistent side effects of querying in this design?

You are probably right... It's not a _persistent data structure_, as Clojure defines it, and neither is it an immutable collection, but it may not violate CQS...

> > Another disadvantage is that because last is unknown, write operations become inefficient. In order to write to the last page, a client would have to start at first and then follow all next links until it reaches the most recent page.
> 
> I have a hard time imagining the use case where it is safe to write new data without first reading the existing data? In that case, why choose an event stream at all?

There are lots of cases where writing without knowing about existing data is perfectly fine, such as error logging, auditing, instrumentation, etc. All of these are examples of _events_ being written.

In a business scenario, you may want to look at previous events in order to decide whether or not to write a new event, but that's not a technical constraint; that's a business constraint.

When it comes to the _technical implementation_ of writing the events, the writer only needs to know _where_ to append the new event.

The problem is that the correct place to append the new event is at the most recent Feed document, but unless you have a (semi-)reliable _last_ link, you'll need to traverse all documents between the _first_ document and the most recent, only for the sake of _finding_ where to append the event. For long event chains, that's awfully inefficient for a single write operation.

> About Alternative 2 - if I understand you correctly, it builds on Alternative 1, so the same disadvantages apply, yes?

No, because it attempts to solve those disadvantages by introducing a _last_ link, so that it can provide both forward and backwards traversal of the doubly-linked list. Basically, you can say that there's no value in having a doubly-linked list if you can only start in one of the ends.

> Observation: The 'last' link only makes sense for the first page. We will not be able to maintain it in the rest of the pages. Trivial, perhaps, but makes for an asymmetry in the model.

Yes, it introduces an asymmetry in the model. As you say, there's no way we can reliably maintain a _last_ link in all the intermediary pages, so the only way to re-introduce symmetry is to remove all the _first_ links. Still, why throw away information?

**Comment by sgryt** [comment]
> What I had in mind was that the implementation of a hypothetical ForwardReadOnlyCursor<T> would update its internal 'bookmark' state whenever it's done enumerating, but will it ever know that the client is done, if the client breaks off prematurely?

I guess we would need a home-grown `IEnumerator<T>` implementation here anyway, so that could update the state in it's MoveNext implementation ?

> There are lots of cases where writing without knowing about existing data is perfectly fine, such as error logging, auditing, instrumentation, etc. All of these are examples of events being written.

Yup, but my point is that in these cases, isn't it overkill to use a doubly-linked event stream? Timestamp'ed entries (or similar) would suffice there, and also have zero risk of update conflicts, which makes them a less risky choice (and faster). 

> No, because it attempts to solve those disadvantages by introducing a last link, so that it can provide both forward and backwards traversal of the doubly-linked list. Basically, you can say that there's no value in having a doubly-linked list if you can only start in one of the ends.

We would still need the state machine for remembering how far the read has proceeded, AFAICT? As I understood it, that was one of the drawbacks you mentioned for Alternative 1, so that's the reasoning behind my comment.
I agree on the usefulness of the 'last' link being available (even if it's only eventually consistent).

> Yes, it introduces an asymmetry in the model. As you say, there's no way we can reliably maintain a last link in all the intermediary pages, so the only way to re-introduce symmetry is to remove all the first links. Still, why throw away information?

Indeed. I'm not arguing that we throw away information. It was just an observation, but it got me thinking about having an entirely separate document for the 'last' link, instead of having it embedded in the first page. That would minimise the latency introduced for reading and writing the 'last' link, as it would likely be very much smaller than the first page, and thus decrease the likelihood of network-latency-introduced concurrency conflicts. It will not remove the problem, but may reduce the probability of it happening. And it would make for a symmetric model across the pages (not a 'first'-and-'last' link symmetry, but rather a uniform page model).

**Comment by ploeh** [comment]
> > What I had in mind was that the implementation of a hypothetical ForwardReadOnlyCursor would update its internal 'bookmark' state whenever it's done enumerating, but will it ever know that the client is done, if the client breaks off prematurely?
> 
> I guess we would need a home-grown IEnumerator<T> implementation here anyway, so that could update the state in it's MoveNext implementation ?

OK, that sounds possible, but still a degree of complexity I'd like to avoid, if possible.

> Yup, but my point is that in these cases, isn't it overkill to use a doubly-linked event stream? Timestamp'ed entries (or similar) would suffice there, and also have zero risk of update conflicts, which makes them a less risky choice (and faster).

The main problem with relying on timestamps is that they have insufficient precision; sometimes, you'll have two (or more) writes happening in the same 'timestamp'.

The other problem is that this model doesn't enable us to perform conditional updates, which is a very desirable trait. From a business perspective, we _want_ to be able to say: _OK, write this event only if nothing has changed compared to the information I had when I made the decision._

The third problem with using a document per event (or event changeset) is that enumeration is slow. This was actually the first model used in AtomEventStore, but as you may recall, [changing to a paged implementation increased performance at least ten-fold](https://github.com/GreanTech/AtomEventStore/pull/30).

> We would still need the state machine for remembering how far the read has proceeded, AFAICT? As I understood it, that was one of the drawbacks you mentioned for Alternative 1, so that's the reasoning behind my comment.

Sure, but the state machine can be part of the client of AtomEventStore, and expressed purely in terms of events and their envelopes, instead of addressed by AtomEventStore. This keeps AtomEventStore simpler, and also (I believe) more flexible. AtomEventStore wouldn't need any stateful classes. It could do what it already does.

This is the model we already use today.

> Indeed. I'm not arguing that we throw away information. It was just an observation, but it got me thinking about having an entirely separate document for the 'last' link, instead of having it embedded in the first page. That would minimise the latency introduced for reading and writing the 'last' link, as it would likely be very much smaller than the first page, and thus decrease the likelihood of network-latency-introduced concurrency conflicts. It will not remove the problem, but may reduce the probability of it happening. And it would make for a symmetric model across the pages (not a 'first'-and-'last' link symmetry, but rather a uniform page model).

Yes, that sounds like a good idea. It doesn't change the underlying principles of this suggested change; it's an implementation detail. I see the point about a separate 'index' page, which could also serve as the 'address' of the entire event list.

This would also mean that, as soon as we've added a _next_ link to a document, we're never going to touch that document again, and we can slap a long cache duration on it.

**Comment by sgryt** [comment]
> The main problem with relying on timestamps is that they have insufficient precision; sometimes, you'll have two (or more) writes happening in the same 'timestamp'.

I'm thinking that an AtomEvent stream is not the right choice of storage model for these kinds of problems, and, as such, I don't think we should design this with such cases in mind. Logging, auditing, instrumentation etc have fire-and-forget semantics, and do not alter the state of the model - and so should not generate events in the stream. 

> The other problem is that this model doesn't enable us to perform conditional updates, which is a very desirable trait. From a business perspective, we want to be able to say: OK, write this event only if nothing has changed compared to the information I had when I made the decision.

Certainly, but doesn't that require that the client to have read the entire stream from the beginning, not from the end? Otherwise, how could such a decision be made? 

> The third problem with using a document per event (or event changeset) is that enumeration is slow.

Yes, ties in nicely with my comments about the (non-)applicability of using the AtomEvents container for logging etc, methinks. 

> Sure, but the state machine can be part of the client of AtomEventStore, and expressed purely in terms of events and their envelopes, instead of addressed by AtomEventStore. This keeps AtomEventStore simpler, and also (I believe) more flexible. AtomEventStore wouldn't need any stateful classes. It could do what it already does.
> 
> This is the model we already use today.

I'm a bit confused here - how is that different if there is no 'last' link?

> This would also mean that, as soon as we've added a next link to a document, we're never going to touch that document again, and we can slap a long cache duration on it.

wOOt!

**Comment by sgryt** [comment]
In any case - I sense a bit of 'straying from the main problem' here. I think that we are close to having fleshed out a workable solution, where the main drawback is a potentially stale 'last' link. 
Or did I miss something vital in your latest comments?

About the staleness of the 'last' link, we could consider making the responsibility of keeping the value updated some sort of Strategy - with a default of giving Writers the responsibility of doing the update. Sometimes, however, the 'last' link may be stale for a long time (infrequent writers scenario), and the penalty of having a stale 'last' link may become noticeable. In that case, it may be worth a CQS violation of having the Readers also help keeping the 'last' link up-to-date ?

**Comment by ploeh** [comment]
Agreed, let's keep it on track. I think at this point we're just talking past each other about certain of the details. My sense is that you agree that my _Alternative 2_ proposal may be a way forward..?

For now, I think we should let the writers take care of any stale _last_ links, and if it ever becomes a problem, we have at least two options:
- Let readers deal with it as well, violating CQS
- Have a background job running that monitors the _last_ link for staleness

**Comment by sgryt** [comment]
Yes, Alternative 2 seems like the only viable option. And I agree on the writers responsibility on updating the 'last' link, I just thought it was worth taking this kind of flexibility into consideration when designing the details ;)

And about the CQS violation when allowing readers to update - it's very analogous to run-of-the-mill caching scenarios (thinking about the 'last' link as a cache does not seem far fetched to me, especially as it can be expected to be stale sometimes) where readers update stuff all the time. So I don't think it's a showstopper to the design.

**Comment by ploeh** [comment]
Good analogy; I buy it :)

**Comment by ploeh** [comment]
AFAICT, this issue can be close when #96, #97, and #98 are all resolved.

**Comment by ploeh** [comment]
Closing, as #96, #97, and #98 are now all resolved.
