### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ploeh** [GreanTech/AtomEventStore#85]
AtomEventStore should have a logo, to be used as icon for its NuGet package, etc.

I already have some vague concept ideas myself, but since I'm not that happy with it, I'd like to solicit other suggestions.

For the moment, then, I'm not going to share my own attempt, since I don't want to influence other people's creative efforts :)

**Comment by josephwoodward** [comment]
Here we go, how about something like this? 
![atomeventstore](https://cloud.githubusercontent.com/assets/1237341/5156071/5d0f03b4-72a1-11e4-98db-9cb16e2e9f06.png)

**Comment by ploeh** [comment]
Looks good. Would you like to submit a pull request?
