### ISSUE TITLE
Convention-based type resolver for Data Contract serializer

### ISSUE THREAD

**Issue by ploeh** [GreanTech/AtomEventStore#94]
If you want to use the `DataContractContentSerializer`, you must supply an appropriate `ITypeResolver` instance. Current options are:
- Use `TypeResolutionTable`
- Provide a custom implementation of `ITypeResolver`

It would be nice with an associated `ITypeResolver` implementation that can scan an assembly and find all types annotated with `[DataContract]` attributes, and pull the associated local and namespace names out of them.

Perhaps it should be an internal class, with a static factory method defined on `DataContractContentSerializer`, in order to signal that this `ITypeResolver` only makes sense used together with `DataContractContentSerializer`. Another option is to make it a nested public class under `DataContractContentSerializer`.

In any case, it would need an `Assembly` object as input. It would then scan that `Assembly` for all matching classes.

**Comment by moodmosaic** [comment]
Wouldn't it be easier by doing something like this, using the existing `TypeResolutionTable`:

``` diff
diff --git a/AtomEventStore.UnitTests/Demo/AcyclicVisitor/Stories.cs b/AtomEventStore.UnitTes..
index 05d6099..ef1b0ed 100644
--- a/AtomEventStore.UnitTests/Demo/AcyclicVisitor/Stories.cs
+++ b/AtomEventStore.UnitTests/Demo/AcyclicVisitor/Stories.cs
@@ -18,20 +18,7 @@ namespace Grean.AtomEventStore.UnitTests.Demo.AcyclicVisitor
             var storage = new AtomEventsInMemory();
             var pageSize = 25;
             var serializer =
-                new DataContractContentSerializer(
-                    new TypeResolutionTable(
-                        new TypeResolutionEntry(
-                            "urn:grean:samples:user-on-boarding",
-                            "user-created",
-                            typeof(UserCreated)),
-                        new TypeResolutionEntry(
-                            "urn:grean:samples:user-on-boarding",
-                            "email-verified",
-                            typeof(EmailVerified)),
-                        new TypeResolutionEntry(
-                            "urn:grean:samples:user-on-boarding",
-                            "email-changed",
-                            typeof(EmailChanged))));
+                DataContractContentSerializer.Create(typeof(Stories).Assembly);
             IObserver<object> obs = new AtomEventObserver<object>(
                 eventStreamId, // a Guid
                 pageSize,      // an Int32
diff --git a/AtomEventStore/DataContractContentSerializer.cs b/AtomEventStore/DataContractCon..
index 83dcf01..0e4eb71 100644
--- a/AtomEventStore/DataContractContentSerializer.cs
+++ b/AtomEventStore/DataContractContentSerializer.cs
@@ -1,6 +1,7 @@
 ﻿using System;
 using System.Collections.Generic;
 using System.Linq;
+using System.Reflection;
 using System.Runtime.Serialization;
 using System.Text;
 using System.Xml;
@@ -105,5 +106,21 @@ namespace Grean.AtomEventStore

             return new XmlAtomContent(value);
         }
+
+        public static DataContractContentSerializer Create(Assembly assembly)
+        {
+            var entries =
+                from t in assembly.GetTypes()
+                from a in t.GetCustomAttributes(
+                              typeof(DataContractAttribute), inherit: false)
+                           .Cast<DataContractAttribute>()
+                where t.IsDefined(a.GetType(), inherit: false)
+                select new TypeResolutionEntry(a.Namespace, a.Name, t);
+
+            var serializer =
+                new DataContractContentSerializer(
+                    new TypeResolutionTable(entries.ToArray()));
+            return serializer;
+        }
     }
 }
```

**Comment by ploeh** [comment]
That's a good observation; I hadn't thought of this at all...

I must admit that I was quite happy that I'd identified more than a single need for implementing `ITypeResolver`, because it would indicate that the interface doesn't violate the [RAP](http://codemanship.co.uk/parlezuml/blog/?postid=934), but now I don't know...

Your proposed solution looks more correct to me :+1:

**Comment by moodmosaic** [comment]
Wouldn't it be more flexible if we accept a `params Type[]` instead of an `Assembly`? That's also compatible with Postel's law (_"[..] be liberal in what you accept."_).

**Comment by ploeh** [comment]
What would you do if the caller calls it with an empty array?

**Comment by moodmosaic** [comment]
I think, I _wouldn't_ throw an exception–that's essentially the same with calling it with an assembly where no type has been decorated with `[DataContract]` attribute.

**Comment by ploeh** [comment]
OK, I buy the argument that it's equivalent to providing an assembly without any appropriate attributes, but don't you think the method should throw an exception if
- It finds no mapped types at all?
- It finds duplicate names?

**Comment by moodmosaic** [comment]
Indeed... That sounds reasonable.

**Comment by moodmosaic** [comment]
Still, wouldn't it be useful to accept `params Type[]`? What if the types are defined in many assemblies?

**Comment by ploeh** [comment]
It might be useful. It does, however, sounds a bit like _gold plating_ to me. It can always be added as a feature later, without breaking existing clients, can't it?

**Comment by moodmosaic** [comment]
Yes, definitely, it can be added later (if necessary). BTW, agreed about gold plating.
